#version: '3.8'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PRIMARY_PARTITION=${PRIMARY_PARTITION}
      - SECONDARY_PARTITION=${SECONDARY_PARTITION}
    volumes:
      - ${PRIMARY_PARTITION}/plex/library:/config
      - plex_data:/plex_data

volumes:
  plex_data:
    driver: local
    driver_opts:
      type: cifs
      device: "//${SMB_ADDR}/plex_data"
      o: "addr=${SMB_ADDR},username=plex,password=${CIFS_PWD},rw,uid=1000,gid=1000,vers=3.0,file_mode=0777,dir_mode=0777"

networks:
  my-network:
